apiVersion: v1
kind: ConfigMap
metadata:
  name: banking-config
  namespace: banking-demo
data:
  POSTGRES_DB: demobankingdb
  POSTGRES_USER: bankadmin
  DB_HOST: postgres
  DB_PORT: "5432"
  BACKEND_PORT: "4000"
  NODE_ENV: production
  FRONTEND_URL: http://frontend
  # Deliberately low max_connections to make pool exhaustion easy to trigger
  postgresql.conf: |
    max_connections = 20
    shared_buffers = 32MB
    work_mem = 2MB
    log_min_duration_statement = 500
    log_connections = on
    log_disconnections = on
    log_checkpoints = on
    log_lock_waits = on
    deadlock_timeout = 1s
    log_statement = 'mod'
