apiVersion: v1
kind: Secret
metadata:
  name: banking-secret
  namespace: banking-demo
type: Opaque
stringData:
  POSTGRES_PASSWORD: bankpass123
  DATABASE_URL: postgresql://bankadmin:bankpass123@postgres:5432/demobankingdb
  JWT_SECRET: demo-jwt-secret-replace-in-prod
